export const dummyJobs = [
    {
        id: 1,
        company_logo: 'https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png',
        job_title: 'Data Scientist',
        company_name: 'Wipro',
        experience: '1 - 2 years',
        salary: '10 - 12 LPA',
        job_location: 'Bangalore',
        roles_responsibility: [
          'Skills Required: Roles and Responsibilities. Java Developers',
          'Software Engineer. We are looking for a Java Developer with experience in building high-performing',
          'scalable, applicationsExperience: 2-4+ years',
        ],
        skills_required: ['Python', 'Ruby', 'Machine Learning', 'Statistics', 'AI', 'ML'],
        posted: 'Posted 60 days ago',
        job_category: 'Data Scientist',
        job_type: 'PREMIUM',
        people_applyed: 50,
    },
    {
        id:2,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Mysore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:3,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Chennai",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:4,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Hyderabad",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:5,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Pune",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:6,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Mysore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:7,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Kollar",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:7,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"chennai",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:8,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Hyderabad",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:9,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Udupi",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:10,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Mangalore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:11,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Bangalore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:12,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Bangalore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:13,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Bangalore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
    {
        id:14,
        company_logo:"https://demoapus1.com/jobtex-new/wp-content/uploads/2023/05/e1.png",
        job_title:"Backend Developer",
        company_name:"Wipro",
        experience:"1 - 2 years",
        salary:"10 - 12 LPA",
        job_location:"Bangalore",
        roles_responsibility:[
            "Skills Required: Roles and Responsibilities. Java Developers",
            "Software Engineer. We are looking for a Java Developer with experience in building high-performing",
            "scalable, applicationsExperience: 2-4+ years",
        ],
        skills_required:["Python","Ruby","Machine Learning","Statistics", "AI", "ML"],
        posted:"Posted 60 days ago",
        job_category:"Backend Developer",
        job_type:"PREMIUM",
        people_applyed:50,
    },
];
